version: '3.8'

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
  
  cypress:
    image: cypress/included:13.15.0  # Use the correct Cypress version
    volumes:
      - .:/e2e
    working_dir: /e2e
    depends_on:
      - vue-app
    environment:
      - CYPRESS_baseUrl=http://vue-app:8081
    command: ["npx", "cypress", "run", "--component"]
